// <auto-generated />
using Loja.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Loja.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250407222236_criandoBancoLoja")]
    partial class criandoBancoLoja : criandoBancoLojaBase
    {
    }
}
